window.EDUOS_PEDAGOGY = [
  {id:"history-decision-under-uncertainty",type:"pedagogy",subject:"history",title:"Decision under Historical Uncertainty",role:"PI",summary:"把学习者放回结果尚未知的信息状态，先权衡约束再看后来证据。",mechanism:"commit → progressive evidence → re-weight → outcome",native:"历史行动者只能使用当时可获得且可信度不一的信息。",conditions:"目标是 contingency；选择确实受约束；后续证据能改变判断。",notWhen:"只需时序、人物或事实复习。",adaptation:"无设备时改成同步投票卡，但保留 reveal 前承诺。",keywords:["commit-before-reveal","contingency","evidence"],provenance:"conversation_given"},
  {id:"history-source-corroboration",type:"pedagogy",subject:"history",title:"Sourcing before Agreement",role:"PI",summary:"先判断来源位置和可知范围，再比较材料是否相互印证。",mechanism:"source position → claim extraction → corroborate/conflict → bounded conclusion",native:"史料不是透明事实容器；沉默、距离和立场都影响可用性。",conditions:"材料之间存在真实的来源差异。",notWhen:"多份材料只是重复同一教材叙述。",adaptation:"初学者先比较两份材料和一个 claim。",keywords:["sourcing","corroboration","provenance"],provenance:"v0_inference"},

  {id:"chinese-evidence-constrained-reading",type:"pedagogy",subject:"chinese",title:"Evidence-constrained Interpretation",role:"PI",summary:"允许多种文本解释，但要求每个判断落回措辞、结构或语境证据。",mechanism:"provisional reading → quote → explain wording → compare → revise",native:"文本解释可以开放，证据约束不能消失。",conditions:"文本存在可辩护的解释空间，且学生能接触原文。",notWhen:"主要障碍仍是基本字词和句法。",adaptation:"弱读者先加 Layered Text，只缩小文本范围，不取消证据。",keywords:["interpretation","text evidence","revision"],provenance:"mixed"},
  {id:"chinese-text-surgery-method",type:"pedagogy",subject:"chinese",title:"Controlled Text Surgery",role:"PI",summary:"只改一个语言特征，通过 A/B 差异推理其表达效果。",mechanism:"commit effect → controlled change → compare → justify",native:"改动必须保持其他语境尽量稳定。",conditions:"目标是句式、词语、修辞或节奏作用。",notWhen:"目标是自由创作或整体润色。",adaptation:"时间短时只做一个词或一个倒装。",keywords:["text surgery","rhetoric","controlled contrast"],provenance:"conversation_given"},

  {id:"civics-near-miss-discrimination",type:"pedagogy",subject:"civics",title:"Concept-boundary Near Miss",role:"PI",summary:"保持诱人的关键词不变，只改变决定概念归属的一项特征。",mechanism:"classify pair → mark decisive phrase → probe simpler pair",native:"政治概念常由主体、行为、关系与制度位置共同限定。",conditions:"存在稳定的课程概念边界和可控制的最小对照。",notWhen:"争议本身没有唯一课程边界。",adaptation:"阅读负荷高时先对齐句式和词长。",keywords:["near miss","boundary","keyword reliance"],provenance:"conversation_given"},
  {id:"civics-principle-deliberation",type:"pedagogy",subject:"civics",title:"Principle Collision Deliberation",role:"PI",summary:"让学生比较多个原则对同一政策的相关性、优先级与代价。",mechanism:"stakeholder view → principle claims → evidence → trade-off statement",native:"规范判断需要说明优先依据，而非找到一个关键词。",conditions:"任务确实涉及原则冲突或政策代价。",notWhen:"问题只是定义识别。",adaptation:"五分钟版只保留两个原则和一个利益相关者。",keywords:["deliberation","trade-off","principle"],provenance:"v0_inference"},

  {id:"math-first-invalid-step",type:"pedagogy",subject:"mathematics",title:"First Invalid Step",role:"PI",summary:"比较相近解法，定位第一处不保持数学关系的变形。",mechanism:"inspect → select line → name invariant → test → transfer",native:"错误定位围绕等价、定义域、守恒或逻辑有效性。",conditions:"错误能被嵌入看似合理的步骤序列。",notWhen:"学生完全没有所需先备程序。",adaptation:"先移除负数等次要负荷，保留同一不变量。",keywords:["error microscope","invariant","diagnostic"],provenance:"conversation_given"},
  {id:"math-representation-coordination",type:"pedagogy",subject:"mathematics",title:"Predict before Representation Shift",role:"PI",summary:"在图像、符号或数值表示切换前先保存预测，再检查映射。",mechanism:"inspect A → predict B → reveal B → explain mapping → revise",native:"映射依赖斜率、参数、结构或不变量，而非视觉相似。",conditions:"两种表示共享明确的数学对象。",notWhen:"第二种表示只是第一种的装饰重复。",adaptation:"生成困难时提供两个 near-miss 目标表示。",keywords:["representation","prediction","graph","equation"],provenance:"mixed"},

  {id:"physics-model-construction",type:"pedagogy",subject:"physics",title:"System-first Model Construction",role:"PI",summary:"先定义系统和外部相互作用，再建立受力模型并预测后果。",mechanism:"choose system → interactions → model → predict → check",native:"力属于相互作用，不属于运动方向。",conditions:"场景足够清楚，系统边界影响模型。",notWhen:"只需介绍箭头记号。",adaptation:"低年级先不求合力大小，只辨来源和方向。",keywords:["system boundary","model construction","force"],provenance:"mixed"},
  {id:"physics-predict-observe-revise",type:"pedagogy",subject:"physics",title:"Prediction–Measurement Revision",role:"PI",summary:"在模拟或测量可见前保存模型预测，再用差异修正模型。",mechanism:"model → quantitative/qualitative prediction → observation → residual → revise",native:"观察受测量误差与理想化条件限制。",conditions:"结果确实能区分候选模型。",notWhen:"动画只是重播已知结论。",adaptation:"无传感器时使用预先记录且带不确定度的数据。",keywords:["prediction","measurement","model revision"],provenance:"v0_inference"},

  {id:"chemistry-representation-completion",type:"pedagogy",subject:"chemistry",title:"Missing Chemical Representation",role:"PI",summary:"给定宏观与微观两层，要求补全符号层并说明对应关系。",mechanism:"inspect linked levels → complete missing level → map → reveal → revise",native:"映射必须遵守物种身份、电荷与原子守恒。",conditions:"给定层足以支持缺失层的推导。",notWhen:"任务退化为记忆方程式。",adaptation:"符号生成过难时改成 near-miss 方程选择。",keywords:["macro micro symbol","completion","mapping"],provenance:"conversation_given"},
  {id:"chemistry-perturb-equilibrium",type:"pedagogy",subject:"chemistry",title:"Perturb–Predict–Reconcile",role:"PI",summary:"先预测扰动后速率和组成，再观察到达新平衡的过程。",mechanism:"baseline → perturb → signed prediction → dynamic reveal → reconcile",native:"区分瞬时速率改变与最终平衡组成。",conditions:"模型能同时显示速率与组成。",notWhen:"只需背诵规则方向。",adaptation:"先只改变浓度一个变量，不同时改变温度。",keywords:["equilibrium","perturbation","rate"],provenance:"v0_inference"},

  {id:"biology-perturb-system",type:"pedagogy",subject:"biology",title:"Perturb–Predict–Trace",role:"PI",summary:"扰动一个变量，预测下游方向与时间，再修改因果关系。",mechanism:"perturb → signed prediction → trace → edit relation → name feedback",native:"组件身份、关系符号和时间延迟都属于生物机制。",conditions:"简化模型仍保留关键生物组件。",notWhen:"用通用恒温器完全替代生物系统。",adaptation:"社交风险高时匿名保存预测。",keywords:["feedback","perturbation","systems"],provenance:"conversation_given"},
  {id:"biology-competing-models",type:"pedagogy",subject:"biology",title:"Competing Biological Models",role:"PI",summary:"让多个机制模型对同一数据作出不同预测，再用新证据淘汰模型。",mechanism:"candidate models → predictions → evidence reveal → revise/eliminate",native:"避免用功能目的语言冒充具体生物机制。",conditions:"候选模型确实有可区分预测。",notWhen:"伪备选项明显荒谬。",adaptation:"初学者保留两个模型和一个决定性数据点。",keywords:["competing models","evidence","mechanism"],provenance:"v0_inference"},

  {id:"geography-spatial-causal-chain",type:"pedagogy",subject:"geography",title:"Spatial Causal Chain",role:"PI",summary:"让学习者把路径、地形、过程和数据连成可修订的空间解释。",mechanism:"locate → trace path → predict process → check data → revise link",native:"位置和尺度必须对因果过程有实际作用。",conditions:"地图／剖面表达的是解释关系。",notWhen:"目标只是地点识记。",adaptation:"静态课件中改成编号链和教师主持的预测暂停。",keywords:["spatial causality","terrain","path","scale"],provenance:"mixed"},
  {id:"geography-scale-shift",type:"pedagogy",subject:"geography",title:"Scale-shift Explanation",role:"PI",summary:"固定现象，改变聚合尺度，比较模式与结论如何变化。",mechanism:"claim at scale A → switch scale → inspect aggregation → qualify claim",native:"尺度不是缩放控件，而是解释单位和证据分辨率。",conditions:"数据在多个可比尺度上可用。",notWhen:"只是为了地图导航。",adaptation:"低数据条件下使用三张预生成尺度快照。",keywords:["scale","aggregation","geography"],provenance:"v0_inference"}
];
