window.EDUOS_CONTENT = [
  {id:"history-constraint-map",type:"content",subject:"history",title:"Decision-time Constraint Map",role:"RC",summary:"只呈现历史行动者当时可获得的地理、兵力、联盟与不确定情报。",target:"赤壁之战中的决策条件",representation:"地图 + 约束卡 + 不确定性标记",domainMove:"把事后叙述还原成当时的信息状态。",codingSurface:"可缩放地图、证据抽屉、分阶段 reveal。",when:"空间位置会改变历史选择时。",not:"不是人物百科地图，也不是事件插图。",keywords:["contingency","map","constraints","decision-time"],provenance:"mixed"},
  {id:"history-source-board",type:"content",subject:"history",title:"Source Provenance Board",role:"RC",summary:"并列来源、作者位置、时间距离和具体主张，让证据差异可检查。",target:"一手／二手史料与叙述立场",representation:"来源卡 + claim 对齐 + provenance 标签",domainMove:"先问谁在什么位置说，再问内容是否可信。",codingSurface:"卡片排序、出处延迟揭示、claim 高亮。",when:"目标是 sourcing、corroboration 或立场判断。",not:"不是把几段材料放进轮播图。",keywords:["sourcing","provenance","corroboration","stance"],provenance:"v0_inference"},
  {id:"history-causal-weight-graph",type:"content",subject:"history",title:"Causal Weight Graph",role:"RC",summary:"让军事、政治、地理、疾病等原因的相对解释力能够被赋权与修订。",target:"多因历史解释",representation:"因果节点 + 权重 + 反事实切换",domainMove:"区分原因存在与原因重要程度。",codingSurface:"滑杆、依赖边、before/after 权重比较。",when:"目标是事后因果解释或反事实。",not:"不是所有原因等权的思维导图。",keywords:["causality","counterfactual","weight","graph"],provenance:"mixed"},

  {id:"chinese-layered-text",type:"content",subject:"chinese",title:"Layered Text",role:"RC",summary:"在原文上按需叠加词义、句法、语境和文化层，不一次性替学生完成解释。",target:"文言理解与阅读支持",representation:"原文锚点 + 可开关支持层",domainMove:"把理解障碍定位到具体词、结构或语境。",codingSurface:"行内批注、层级开关、支持使用日志。",when:"阅读门槛妨碍后续解释时。",not:"不是整段白话翻译覆盖原文。",keywords:["文言","layered text","syntax","context"],provenance:"conversation_given"},
  {id:"chinese-emotion-river",type:"content",subject:"chinese",title:"Emotion River",role:"RC",summary:"把情绪转折作为可争论的时序曲线，并始终与原文证据相连。",target:"《赤壁赋》等文本的情绪结构",representation:"段落轴 + 相对强度曲线 + 引文锚点",domainMove:"提出情绪轨迹并用措辞支持，而非只贴情绪标签。",codingSurface:"拖动节点、引文连接、同伴曲线叠加。",when:"顺序和转折本身是解释对象。",not:"不是预填 happy/sad emoji 的装饰波浪。",keywords:["赤壁赋","emotion river","evidence","turning point"],provenance:"conversation_given"},
  {id:"chinese-text-surgery",type:"content",subject:"chinese",title:"Text Surgery",role:"RC",summary:"删除、替换或重排一个语言特征，再比较意义、节奏或语气的变化。",target:"修辞、句式与表达效果",representation:"原句／改句同步差异视图",domainMove:"通过受控改写显露形式与效果的关系。",codingSurface:"词块替换、diff 高亮、朗读 A/B。",when:"目标是修辞或语言选择的效果。",not:"不是自由改写器或自动润色器。",keywords:["rhetoric","revision","diff","sentence"],provenance:"conversation_given"},

  {id:"civics-near-miss-materials",type:"content",subject:"civics",title:"Near-miss Material Pair",role:"RC",summary:"保持政府等表面提示不变，只改变决定概念归属的主体行为。",target:"政治概念边界",representation:"句式对齐的两张材料卡",domainMove:"控制变量式地区分关键词匹配与概念判断。",codingSurface:"同步高亮、decisive phrase 选择、二次 pair。",when:"学生似乎依赖关键词分类。",not:"不是两道随机的困难选择题。",keywords:["near miss","concept boundary","依法行政","keyword"],provenance:"mixed"},
  {id:"civics-principle-collision",type:"content",subject:"civics",title:"Principle Collision Matrix",role:"RC",summary:"把同一政策对不同原则、权利与责任的支持和张力并列呈现。",target:"政策权衡与规范冲突",representation:"原则 × 方案矩阵 + 证据格",domainMove:"承认原则可能同时相关，再要求说明优先次序。",codingSurface:"权重、证据引用、利益相关者切换。",when:"没有单一关键词能直接决定结论。",not:"不是给每个政策贴唯一正确原则。",keywords:["trade-off","principle","policy","stakeholder"],provenance:"v0_inference"},
  {id:"civics-argument-bridge",type:"content",subject:"civics",title:"Claim–Evidence–Warrant Bridge",role:"RC",summary:"显示观点、材料证据和解释桥之间缺失或错配的位置。",target:"政治材料论证",representation:"三段式 argument board",domainMove:"不把摘抄材料当成已经完成论证。",codingSurface:"拖放关系、缺失桥提示、反例插入。",when:"学生有证据但解释不到原则。",not:"不是万能作文模板。",keywords:["claim","evidence","warrant","argument"],provenance:"v0_inference"},

  {id:"math-balance-transform",type:"content",subject:"mathematics",title:"Equality-preserving Balance",role:"RC",summary:"同步显示方程两边进行同一操作，突出等式保持而非换边口诀。",target:"一元一次方程的等价变形",representation:"符号步骤 + 可选天平对应",domainMove:"把每一步解释为保持解集的操作。",codingSurface:"同步动画、操作按钮、代回检查。",when:"目标是解释等式不变量。",not:"不是用天平替代所有符号推理。",keywords:["equation","balance","invariant","algebra"],provenance:"mixed"},
  {id:"math-error-lines",type:"content",subject:"mathematics",title:"Aligned Solution Lines",role:"RC",summary:"逐行对齐两份相似解法，使第一处不合法变形可被准确定位。",target:"代数错误辨析",representation:"并排步骤 + 行级选择",domainMove:"寻找 first invalid step，而不只判断最终答案。",codingSurface:"行锁定、规则标注、substitution check。",when:"需要区分概念错误和计算 slip。",not:"不是提前用红绿颜色标答案。",keywords:["error microscope","first invalid step","algebra"],provenance:"mixed"},
  {id:"math-parameter-intersection",type:"content",subject:"mathematics",title:"Parameter–Graph–Equation Link",role:"RC",summary:"参数、图像与方程解同步变化，支持先预测再拖动。",target:"函数与方程的表示协调",representation:"滑杆 + 图像 + 代数表达",domainMove:"把参数变化解释为图像结构变化。",codingSurface:"实时绘图、预测 ghost、intersection 标记。",when:"目标是连接多个数学表示。",not:"不是只供观看的 graphing demo。",keywords:["function","parameter","graph","equation"],provenance:"mixed"},

  {id:"physics-force-scene",type:"content",subject:"physics",title:"System-boundary Force Scene",role:"RC",summary:"先明确研究系统，再把场景中的外部相互作用映射为受力箭头。",target:"受力分析",representation:"场景 + 系统边界 + 自由体图",domainMove:"每个力必须有外部作用源。",codingSurface:"圈选系统、箭头生成、source 标签。",when:"学生把运动、速度或反作用力混入受力图。",not:"不是拖箭头匹配隐藏图片。",keywords:["free body diagram","system boundary","force"],provenance:"mixed"},
  {id:"physics-motion-linked-views",type:"content",subject:"physics",title:"Motion–Graph–Equation Triplet",role:"RC",summary:"同一运动同时以场景、图像和方程呈现，并允许缺失一层让学生补全。",target:"运动学表示协调",representation:"运动动画 + x–t/v–t 图 + 方程",domainMove:"用斜率、截距和趋势建立跨表示映射。",codingSurface:"同步时间游标、ghost prediction、方程选择。",when:"会算但无法解释图像，或相反。",not:"不是三个互不关联的面板。",keywords:["motion","graph","equation","slope"],provenance:"conversation_given"},
  {id:"physics-measurement-strip",type:"content",subject:"physics",title:"Measurement & Uncertainty Strip",role:"RC",summary:"并列原始测量、估计区间和模型预测，不把实验读数显示成绝对真值。",target:"实验数据与不确定性",representation:"测量轨迹 + 误差带 + 模型线",domainMove:"比较差异是否大于测量不确定度。",codingSurface:"重复测量、误差条、残差视图。",when:"目标是实验推理而非理想模型演示。",not:"不是给仪器加随机噪声的动画。",keywords:["measurement","uncertainty","residual","experiment"],provenance:"v0_inference"},

  {id:"chemistry-three-level",type:"content",subject:"chemistry",title:"Macro–Micro–Symbol Linked View",role:"RC",summary:"同步组织可观察现象、粒子变化与符号表达，并要求跨层映射。",target:"化学表征协调",representation:"烧杯现象 + 粒子模型 + 方程",domainMove:"区分观察、模型解释与符号记述。",codingSurface:"联动高亮、隐藏一层、粒子到符号连线。",when:"学生会写方程但解释不了粒子变化。",not:"不是三张图同时出现就算对齐。",keywords:["macro","micro","symbol","particle","equation"],provenance:"conversation_given"},
  {id:"chemistry-particle-collision",type:"content",subject:"chemistry",title:"Particle Event Sequence",role:"RC",summary:"以离散事件显示碰撞、键变化与产物形成，避免连续魔法式 morph。",target:"反应微观机制",representation:"粒子事件帧 + 守恒计数",domainMove:"用粒子身份与数量解释反应。",codingSurface:"逐帧推进、物种过滤、守恒计数器。",when:"微观机制对宏观现象有解释价值。",not:"不是漂亮但不守恒的粒子动画。",keywords:["particle","reaction","conservation","mechanism"],provenance:"v0_inference"},
  {id:"chemistry-equilibrium-shift",type:"content",subject:"chemistry",title:"Equilibrium Perturbation View",role:"RC",summary:"把正逆反应速率、粒子群与宏观浓度在扰动前后联动。",target:"化学平衡",representation:"速率曲线 + 粒子状态 + 浓度面板",domainMove:"解释新平衡如何形成，而非只背移动方向。",codingSurface:"扰动控制、预测锁定、动态曲线。",when:"目标是平衡机制与预测。",not:"不是勒夏特列原理关键词选择器。",keywords:["equilibrium","perturbation","rate","concentration"],provenance:"v0_inference"},

  {id:"biology-feedback-loop",type:"content",subject:"biology",title:"Feedback Loop + Variable Trace",role:"RC",summary:"将组件关系和随时间变化的变量轨迹并列，避免把圆形图当成机制。",target:"生理调节与反馈",representation:"因果环 + 时间曲线",domainMove:"追踪扰动、检测、响应和恢复之间的符号关系。",codingSurface:"变量扰动、关系编辑、时间 trace。",when:"目标是系统调节的因果机制。",not:"不是顺时针播放的定义动画。",keywords:["feedback","homeostasis","variable trace","system"],provenance:"conversation_given"},
  {id:"biology-genetics-model",type:"content",subject:"biology",title:"Inheritance Model Revision",role:"RC",summary:"从家系或后代数据出发，让学生修订等位基因与概率模型。",target:"遗传模式与证据",representation:"家系／交配结果 + 模型假设",domainMove:"用数据区分多个遗传解释。",codingSurface:"模型选择、预测区间、反例个体 reveal。",when:"目标是模型选择，不只是 Punnett square 操作。",not:"不是已知模型下的机械填格。",keywords:["genetics","model revision","pedigree","probability"],provenance:"v0_inference"},
  {id:"biology-experiment-variables",type:"content",subject:"biology",title:"Experiment Variable Canvas",role:"RC",summary:"把处理、响应、控制变量和可能混杂安排进一个可检查实验结构。",target:"生物实验设计",representation:"实验组结构 + 数据预览",domainMove:"让因果主张对应可区分的实验比较。",codingSurface:"变量槽位、组间对齐、伪数据 preview。",when:"目标是设计或评价实验。",not:"不是通用项目管理画布。",keywords:["experiment","control variable","causal inference"],provenance:"v0_inference"},

  {id:"geography-terrain-path",type:"content",subject:"geography",title:"Terrain Cross-section + Moisture Path",role:"RC",summary:"把平面路径与垂直地形剖面连起来，显露气流抬升和阻挡。",target:"四川盆地气候因果解释",representation:"定位图 + 剖面 + 水汽路径",domainMove:"用空间关系构建气候因果链。",codingSurface:"路径绘制、剖面对齐、uplift 标注。",when:"地形位置在解释中具有因果作用。",not:"不是旋转 3D 地形加城市事实。",keywords:["四川盆地","terrain","moisture path","climate"],provenance:"mixed"},
  {id:"geography-multiscale",type:"content",subject:"geography",title:"Multi-scale Place Comparator",role:"RC",summary:"同一现象在社区、区域与国家尺度切换，并显式显示尺度变化带来的解释损失。",target:"地理尺度推理",representation:"同步多尺度地图 + 指标",domainMove:"区分现象变化与聚合尺度变化。",codingSurface:"尺度切换、区域聚合、可比指标锁定。",when:"结论会随空间尺度改变。",not:"不是普通地图缩放。",keywords:["scale","aggregation","map","comparison"],provenance:"v0_inference"},
  {id:"geography-flow-map",type:"content",subject:"geography",title:"Human Flow & Constraint Map",role:"RC",summary:"把人口或资源流动与机会、成本和边界条件联动。",target:"人口迁移与人文地理",representation:"流线 + 来源／目的地 + 约束层",domainMove:"解释流动为何发生，而非只显示数量。",codingSurface:"流线筛选、情景变量、stakeholder view。",when:"目标是人地关系和空间选择。",not:"不是越粗越重要的装饰流线图。",keywords:["migration","flow","human geography","constraint"],provenance:"v0_inference"}
];
