window.EDUOS_SKILLS = [
  {id:"skill-historical-intent-router",type:"skill",subject:"history",title:"historical-intent-router",role:"PS",summary:"区分时序、因果、contingency、sourcing 与 perspective，避免把所有历史内容路由成时间线。",trigger:"教师给出历史主题但没有明确学习动作，或只说‘做个可视化’。",refusal:"不因历史主题自动选择地图、时间线或角色扮演。",input:"topic, teacher_goal?, learners, time, devices, design_authority",output:"intent hypothesis, preferred artifact, rejected alternative, clarifying fork",searches:["content/history","pedagogy/history","worked-examples/history","contingency","sourcing"],keywords:["router","history","intent","artifact"],provenance:"mixed"},
  {id:"skill-historical-evidence-probe",type:"skill",subject:"history",title:"historical-evidence-probe",role:"PS",summary:"从历史选择、引文和修订中生成多个解释，并提出最便宜的下一证据。",trigger:"已有 learner commitment、source selection 或 causal weighting。",refusal:"不把与标准答案不同的选择直接标成 misconception。",input:"observations[], available_sources, target_reasoning",output:"possible_interpretations[], next_discriminating_probe",searches:["source provenance","claim evidence bridge","decision-time constraints"],keywords:["probe","evidence","history","hypothesis"],provenance:"v0_inference"},

  {id:"skill-chinese-intent-router",type:"skill",subject:"chinese",title:"chinese-text-intent-router",role:"PS",summary:"同一篇文本按文言理解、情绪结构、修辞效果或论证变化路由到不同 artifact。",trigger:"教师给出篇目但没有说要学生理解、解释还是改写什么。",refusal:"不因为已有 Emotion River 就把《赤壁赋》的所有目标都路由过去。",input:"text, instructional_intent?, learner_barrier, time",output:"Layered Text | Emotion River | Text Surgery | Evidence Board recommendation",searches:["content/chinese","same-content-different-intent","worked-examples/chinese"],keywords:["赤壁赋","router","layered text","emotion river"],provenance:"conversation_given"},
  {id:"skill-literary-evidence-probe",type:"skill",subject:"chinese",title:"literary-evidence-probe",role:"PS",summary:"区分字面理解、证据选择和解释分歧，为文本判断生成下一 probe。",trigger:"学习者提交情绪、主题、修辞效果或段意判断。",refusal:"不把另一种可辩护阅读判成错误。",input:"claim, quote?, explanation?, passage",output:"observations, possible interpretations, evidence-focused probe",searches:["Layered Text","Evidence Board","claim-with-evidence"],keywords:["text evidence","probe","interpretation"],provenance:"mixed"},

  {id:"skill-civics-boundary-probe",type:"skill",subject:"civics",title:"civics-concept-boundary-probe",role:"PS",summary:"围绕政治概念的决定性边界生成控制变量式 near-miss。",trigger:"教师怀疑学生依赖主体或关键词匹配概念。",refusal:"不生成多个无关特征同时变化的‘难题对’。",input:"target_concept, seductive_cue, decisive_feature, reading_level",output:"aligned pair, decisive phrase key, follow-up pair",searches:["near-miss","content/civics","worked-examples/civics"],keywords:["concept boundary","near miss","politics"],provenance:"mixed"},
  {id:"skill-civics-argument-repair",type:"skill",subject:"civics",title:"civics-argument-repair",role:"PS",summary:"判断政治材料回答缺失的是 claim、evidence 还是 warrant，并选择最小修复动作。",trigger:"学生已经有部分材料分析，但论证链断裂。",refusal:"不直接替学生生成完整标准答案。",input:"prompt, student_claim, cited_material, explanation",output:"observed gap, candidate interpretations, one repair prompt",searches:["claim evidence warrant","principle collision","worked examples"],keywords:["argument","warrant","repair"],provenance:"v0_inference"},

  {id:"skill-math-error-probe",type:"skill",subject:"mathematics",title:"mathematical-error-probe",role:"PS",summary:"从第一处无效步骤生成能区分不变量理解、符号处理和 slip 的 probe。",trigger:"学生提交步骤或在两种解法中做出选择。",refusal:"不从一个错误断言稳定 misconception。",input:"problem, student_steps, target_invariant, confidence?",output:"first observable divergence, hypotheses, minimal transfer item",searches:["error microscope","aligned solution lines","invariant"],keywords:["math","error","probe","first invalid step"],provenance:"conversation_given"},
  {id:"skill-math-representation-router",type:"skill",subject:"mathematics",title:"math-representation-router",role:"PS",summary:"判断该生成静态解释、linked visualization、completion task 还是 diagnostic contrast。",trigger:"已有数学内容或图形，但教学意图与 learner action 未定。",refusal:"不把所有可视化都升级成带诊断的互动练习。",input:"content, goal, existing_asset?, learner_state?, authority",output:"representation role, interaction need, reuse/synthesis decision",searches:["math visualization","content/mathematics","pedagogy/mathematics"],keywords:["representation","router","reuse","synthesis"],provenance:"mixed"},

  {id:"skill-physics-model-builder",type:"skill",subject:"physics",title:"physics-model-builder",role:"PS",summary:"从场景和目标选择系统边界、模型元素与预测 reveal。",trigger:"目标涉及力、运动或实验模型构建。",refusal:"不生成没有作用源标签的箭头匹配游戏。",input:"scene, target_system, prior_knowledge, goal",output:"representation plan, model steps, observable evidence",searches:["free body diagram","system boundary","prediction observation"],keywords:["physics","model","force","system"],provenance:"mixed"},
  {id:"skill-physics-signal-interpreter",type:"skill",subject:"physics",title:"physics-signal-interpreter",role:"PS",summary:"将受力图和运动预测拆为观察，并区分 source、vector sum 与 motion-as-force 假设。",trigger:"已有箭头、来源标签或运动预测记录。",refusal:"不因多画一个箭头就自动诊断 action–reaction confusion。",input:"system_boundary, forces[], prediction, revision",output:"possible interpretations, next scene perturbation",searches:["force model","motion linked views","measurement uncertainty"],keywords:["learner signal","physics","probe"],provenance:"v0_inference"},

  {id:"skill-chemistry-representation-router",type:"skill",subject:"chemistry",title:"chemistry-representation-router",role:"PS",summary:"决定宏观、微观、符号三层中哪些展示、隐藏或让学习者补全。",trigger:"化学内容需要解释或练习，但三层角色未定。",refusal:"不把三层并排等同于表征协调。",input:"reaction_or_system, goal, known_representation_gap, learner_level",output:"linked views, missing layer, mapping action, simplification",searches:["macro micro symbol","representation completion","content/chemistry"],keywords:["chemistry","representation","router"],provenance:"conversation_given"},
  {id:"skill-chemistry-probe",type:"skill",subject:"chemistry",title:"chemical-representation-probe",role:"PS",summary:"区分符号生成、粒子身份、守恒和跨层因果困难。",trigger:"学生选择或生成方程、粒子或现象解释。",refusal:"不把方程错误直接解释为化学机制不懂。",input:"observations across macro_micro_symbol",output:"hypotheses, one layer-reduced probe",searches:["spectator species","particle mapping","equation"],keywords:["chemistry","probe","particle","symbol"],provenance:"mixed"},

  {id:"skill-biology-system-router",type:"skill",subject:"biology",title:"biology-system-router",role:"PS",summary:"为反馈、遗传、生态或实验问题选择因果环、竞争模型或变量画布。",trigger:"教师给出生物系统但未说明要解释机制、比较模型还是设计实验。",refusal:"不把通用流程图当作生物机制。",input:"system, intent, variables, time, authority",output:"domain representation, learner action, simplification boundary",searches:["feedback loop","competing models","experiment variables"],keywords:["biology","system","router"],provenance:"v0_inference"},
  {id:"skill-biology-feedback-probe",type:"skill",subject:"biology",title:"biology-feedback-probe",role:"PS",summary:"从变量预测和关系编辑中区分符号错误、组件角色、时滞与目的论解释。",trigger:"学习者已经扰动系统或画出反馈关系。",refusal:"不把‘系统想恢复’接受为充分机制解释。",input:"perturbation, predictions, relation_edits, explanation",output:"observations, hypotheses, component-freeze probe",searches:["feedback","variable trace","mechanism versus purpose"],keywords:["feedback","probe","teleology"],provenance:"mixed"},

  {id:"skill-geography-intent-router",type:"skill",subject:"geography",title:"geography-intent-router",role:"PS",summary:"区分定位、空间比较、因果解释、尺度推理与人地流动，避免默认 3D 地图。",trigger:"教师说‘做个地理可视化’或只给出地区。",refusal:"不因地理学科自动选择地图；表示必须服务目标关系。",input:"place_or_process, goal?, scale, data, devices",output:"map/cross-section/chart/flow recommendation and rejected alternative",searches:["content/geography","spatial causal chain","scale shift"],keywords:["geography","router","map","scale"],provenance:"conversation_given"},
  {id:"skill-geography-causal-probe",type:"skill",subject:"geography",title:"spatial-causal-probe",role:"PS",summary:"区分地图／剖面读取、过程机制、来源知识和尺度混淆。",trigger:"学习者提交路径、地点、剖面标注或气候解释。",refusal:"不从一条错误路径直接诊断气候机制缺失。",input:"path, annotations, prediction, selected_data",output:"possible interpretations, simplified spatial probe",searches:["terrain cross-section","moisture path","multi-scale"],keywords:["geography","causal","probe","scale"],provenance:"mixed"}
];
