const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const FILTERS={all:'全部',content:'内容表征',scaffold:'学习脚手架',diagnostic:'诊断探针',metacog:'监控与迁移'};
const GROUPS={content:'CONTENT PRIMITIVES · 内容底座',scaffold:'SCAFFOLDS · 支持与撤除',diagnostic:'DIAGNOSTIC PROBES · 区分性探针',metacog:'MONITORING · 数学自检'};

const TOOLS=[
 {id:'M01',kind:'content',symbol:'↔',name:'联动表征台',en:'Linked Representations',claim:'一个动作同时改变图、表、式和数值，学生才能看见它们表达的是同一个数学对象。',trigger:'学生能在某一种表征中做题，但换成图像、表格或符号就像新知识。',success:'能用一种表征预测另一种表征的变化。',fade:'先撤桥接文字，再撤颜色对应，最后只保留任务需要的表征。',not:'不是把四种表征放在四个卡片里；必须由同一次操作同步驱动。',slots:['数学对象','联动表征','颜色对应','可变参数'],origin:'已有底座：math-viz-kit V2；此处增加预测与 fade。',contract:'input: object + representations[]\naction: manipulate_once\noutput: cross_rep_prediction\nfade: bridge_text -> color -> extra_view',
 demo:`<div class="m-toolbar"><b>y = 2x + 1</b><label>x = <span data-xv>1</span></label><input data-x type="range" min="-2" max="3" value="1"></div><div class="linked"><div class="graph"><div class="line-y"></div><div class="moving-dot"></div></div><div class="linked-side"><div class="formula-box">y = 2·<b data-fx>1</b> + 1 = <b data-fy>3</b></div><table class="value-table"><tr><td>x</td><td>y</td></tr><tr><td>-1</td><td>-1</td></tr><tr class="hot"><td data-tx>1</td><td data-ty>3</td></tr><tr><td>2</td><td>5</td></tr></table></div></div><div class="m-feedback" data-out>拖动 x：蓝点、代入式和表格同一行会一起改变。</div>`,
 init(r){let x=$('[data-x]',r);x.oninput=()=>{let v=+x.value,y=2*v+1;$('[data-xv]',r).textContent=v;$('[data-fx]',r).textContent=v;$('[data-fy]',r).textContent=y;$('[data-tx]',r).textContent=v;$('[data-ty]',r).textContent=y;$('.moving-dot',r).style.left=(48+v*7)+'%';$('.moving-dot',r).style.top=(52-y*5)+'%';$('[data-out]',r).textContent=`x 增加 1 时，表中 y 增加 2，图上的点沿同一条直线移动；三个变化来自同一个函数规则。`}}},
 {id:'M02',kind:'content',symbol:'≡',name:'动态不变量实验器',en:'Invariant Explorer',claim:'允许对象自由变化，同时把始终不变的量固定显示；“无论怎样都成立”才是数学关系。',trigger:'学生把定理理解成某张特殊图上的事实，换一个形状就不敢使用。',success:'主动说出变了什么、不变什么，并提出一般化。',fade:'撤掉不变量读数，让学生先预测，再用测量复核。',not:'不是拖动后只更新一堆数字；视觉注意必须集中在一个不变量。',slots:['可变自由度','目标不变量','极端位置','测量方式'],origin:'已有底座：math-viz-kit V1/V8；新增预测—极端例检验。',contract:'input: geometry + degrees_of_freedom\naction: vary_shape\noutput: invariant_claim + extreme_test\nnext: M13 boundary_probe',
 demo:`<div class="m-toolbar"><b>同底同高的三角形</b><span>拖动顶点</span><button data-edge>跳到极端位置</button></div><div class="invariant-stage"><div class="parallel a"></div><div class="parallel b"></div><div class="triangle-shape"></div><div class="apex"></div><div class="area-readout">底 = 6　高 = 4<br><b>面积 = 12</b></div></div><div class="m-feedback" data-out>拖动橙色顶点：形状一直变，底和高不变，因此面积不变。</div>`,
 init(r){let apex=$('.apex',r),stage=$('.invariant-stage',r),drag=false;apex.onpointerdown=e=>{drag=true;apex.setPointerCapture(e.pointerId)};apex.onpointermove=e=>{if(!drag)return;let b=stage.getBoundingClientRect(),left=Math.max(20,Math.min(b.width-25,e.clientX-b.left));apex.style.left=left+'px';$('.triangle-shape',r).style.left=Math.max(0,left-120)+'px';$('[data-out]',r).textContent='顶点位置改变了，斜边与角都改变；但它仍在同一条平行线上，所以高和面积没有改变。'};apex.onpointerup=()=>drag=false;$('[data-edge]',r).onclick=()=>{apex.style.left='20px';$('.triangle-shape',r).style.left='0';$('[data-out]',r).textContent='即使三角形变得很斜，面积仍为 12。极端位置正在检验“形状看起来不同”是否影响结论。'}}},
 {id:'M03',kind:'content',symbol:'▦',name:'例子空间生成器',en:'Example-space Generator',claim:'固定大部分条件、只系统改变一个维度，让学生从例子集合中看见分类边界。',trigger:'学生见过几个例题，却不知道这些题为什么属于不同类型。',success:'能命名控制分类的变量，并自己生成一个边界例。',fade:'从系统给例子，逐步过渡到学生自己填参数生成例子。',not:'不是随机题生成器；随机变化太多，反而看不见分类变量。',slots:['固定条件','变化维度','边界值','反例'],origin:'新推断：用 variation theory 补足现有单工具 catalog。',contract:'input: parameter_space + held_constant\naction: vary_one_dimension\noutput: classification_rule + learner_example\nfade: curated_cases -> blank_case',
 demo:`<div class="m-toolbar"><b>x² + bx + 4 = 0</b><span>只改变 b，其他保持不变</span></div><div class="case-grid"><button class="case" data-b="5"><div class="mini-parabola"></div><b>b=5</b><div class="roots">两个实根</div></button><button class="case active" data-b="4"><div class="mini-parabola"></div><b>b=4</b><div class="roots">一个重根</div></button><button class="case" data-b="3"><div class="mini-parabola"></div><b>b=3</b><div class="roots">无实根</div></button></div><div class="m-feedback" data-out>三个例子只改变 b。点击比较，找出“两个根”和“没有实根”之间的边界。</div>`,
 init(r){$$('[data-b]',r).forEach(b=>b.onclick=()=>{$$('[data-b]',r).forEach(x=>x.classList.remove('active'));b.classList.add('active');let v=+b.dataset.b,d=v*v-16;$('[data-out]',r).textContent=`b=${v} 时，判别式 Δ=${d}。真正控制分类的是 Δ 的正、零、负；b=±4 是边界例。`})}},
 {id:'M04',kind:'content',symbol:'≈',name:'逼近显微镜',en:'Approximation Microscope',claim:'让近似过程、误差和极限同时可见；增加步骤不是目的，误差如何缩小才是核心。',trigger:'学生把极限或数值方法理解成“算更多次会更准”，但说不出为什么。',success:'能预测增加分割数后误差方向，并指出上/下界怎样夹逼。',fade:'先撤实时误差，再让学生估计误差数量级。',not:'不是只放一个 n 滑杆和漂亮曲线；必须显示近似值与误差之间的关系。',slots:['目标量','近似方法','n 范围','误差/界'],origin:'已有底座：黎曼和、Taylor、ε-δ；新增误差预测 scaffold。',contract:'input: target + approximation(n)\naction: predict_error_then_refine\noutput: error_trend + stopping_rule\nnext: M06 predict | M15 monitor',
 demo:`<div class="m-toolbar"><b>∫₀¹ x² dx</b><label>矩形数 n=<span data-nv>4</span></label><input data-n type="range" min="2" max="12" value="4"><button data-hide>隐藏误差</button></div><div class="riemann"><div class="curve"></div><div class="rects" data-rects></div></div><div class="m-feedback" data-out>近似值 0.4688；真实值 0.3333；误差 0.1354。</div>`,
 init(r){let input=$('[data-n]',r),hidden=false;function draw(){let n=+input.value;$('[data-nv]',r).textContent=n;$('[data-rects]',r).innerHTML=Array.from({length:n},(_,i)=>`<i style="--h:${30+Math.pow((i+1)/n,2)*190}px"></i>`).join('');let sum=0;for(let i=1;i<=n;i++)sum+=Math.pow(i/n,2)/n;let err=sum-1/3;$('[data-out]',r).textContent=hidden?`n=${n}。先估计误差比 n=${Math.max(2,n-1)} 时更大还是更小，再揭示。`:`右端点和 ≈ ${sum.toFixed(4)}；误差 ${err.toFixed(4)}。n 增大时矩形宽度缩小，误差趋向 0。`}input.oninput=draw;$('[data-hide]',r).onclick=e=>{hidden=!hidden;e.target.classList.toggle('active',hidden);draw()};draw()}},
 {id:'M05',kind:'content',symbol:'=',name:'等价变换账本',en:'Structure-preserving Transformation',claim:'每一步不仅显示“做了什么”，还显示什么数学结构被保持，例如等式两边同加同减仍保持解集。',trigger:'学生把移项、约分、行变换记成符号搬运口诀。',success:'能为一步变换说出保持的对象，并拒绝一个不保持结构的近似操作。',fade:'先撤操作说明，再撤两边同步动画，只留下变换前后。',not:'不是自动解题器；最终答案不是中心，保持了什么才是中心。',slots:['初始对象','允许变换','保持量','非法近似步'],origin:'扩展自 math-viz-kit 天平/高斯消元：从过程展示转向结构保持。',contract:'input: state + legal_operations\naction: apply_to_structure\noutput: transformed_state + preserved_property\nnext: M10 self_explain | M08 error_probe',
 demo:`<div class="m-toolbar"><b>解 3x + 5 = 17</b><button data-next>执行下一步</button><button data-wrong>试一个非法步骤</button></div><div class="transform-ledger"><div class="equation-row"><code>3x + 5 = 17</code><span class="reason">初始等式</span></div><div data-rows></div></div><div class="m-feedback" data-out>每一步都必须对等式两边执行相同操作，解集才保持不变。</div>`,
 init(r){let step=0,rows=[['3x = 12','两边同时减 5'],['x = 4','两边同时除以 3']];$('[data-next]',r).onclick=()=>{if(step<2){$('[data-rows]',r).insertAdjacentHTML('beforeend',`<div class="equation-row"><code>${rows[step][0]}</code><span class="reason">${rows[step][1]}<br>解集保持</span></div>`);$('[data-out]',r).textContent=`${rows[step][1]}：改变了式子的外观，但没有改变满足等式的 x。`;step++}};$('[data-wrong]',r).onclick=()=>{$('[data-rows]',r).insertAdjacentHTML('beforeend','<div class="equation-row changed"><code>3x = 17 - 5 / 3</code><span class="reason">❌ 只除了一部分<br>不保持等价</span></div>');$('[data-out]',r).textContent='非法步不是“算错了一个数”，而是操作没有作用于完整结构，因此解集不再相同。'}}},
 {id:'M06',kind:'scaffold',symbol:'?',name:'预测后揭示',en:'Predict before Reveal',claim:'在动态图、下一步或答案出现前，先要求一个有方向、可比较的预测。',trigger:'学生只是看动画或跟着步骤点“下一步”，没有形成可检验的预期。',success:'预测理由引用了当前数学关系；预测错也能明确指出模型哪里需要修正。',fade:'从三选一预测，转为方向输入，最后只在边界处预测。',not:'不是在每一步都加一道选择题；只在结果具有诊断价值的转折点承诺。',slots:['当前状态','可预测变化','揭示结果','修订问题'],origin:'新 scaffold：把现有动态工具从观看模式改造成模型检验。',contract:'trigger: before_dynamic_change\ninteraction: commit_direction -> reveal\noutput: prediction + revision\nfade: choices -> open_prediction -> none',
 demo:`<div class="predict-box"><h3>函数 y=kx+1：当 k 从 1 增大到 3，直线会怎样？</h3><div class="predict-options"><button data-p="rotate">绕截距点变陡</button><button data-p="up">整体向上平移</button><button data-p="parallel">保持平行</button></div><button data-reveal disabled>运行变化</button><div class="reveal-panel" data-result>结果：直线绕固定的 y 轴截距 (0,1) 旋转并变陡。请修改你的参数模型。</div></div>`,
 init(r){let p='';$$('[data-p]',r).forEach(b=>b.onclick=()=>{$$('[data-p]',r).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');p=b.dataset.p;$('[data-reveal]',r).disabled=false});$('[data-reveal]',r).onclick=()=>{$('[data-result]',r).classList.add('show');$('[data-result]',r).innerHTML=(p==='rotate'?'预测与结果一致。':'预测需要修正。')+' <b>k 控制斜率，b 控制纵截距；只改变 k 不会让整条线平移。</b>'}}},
 {id:'M07',kind:'scaffold',symbol:'□',name:'Worked-example 递减器',en:'Worked-example Fading',claim:'完整例题不是终点；解释、步骤和计算槽必须按掌握证据逐步消失。',trigger:'学生能看懂老师或 AI 的完整解法，却面对相似题仍不会开始。',success:'在空缺逐渐前移时仍能完成，并能处理表面不同的迁移题。',fade:'完整示范 → 最后一步留空 → 中间步骤留空 → completion problem → 独立题。',not:'不是把答案一次性隐藏，也不是固定的“例题后一道练习”。',slots:['完整解法','可淡出槽位','近迁移题','成功阈值'],origin:'新核心 scaffold；edulab 的同步步骤可作为可靠内容底座。',contract:'input: verified_steps[] + mastery_events\naction: hide_next_slot\noutput: completion_accuracy + hint_cost\nfade_rule: 2 successes -> earlier blank',
 demo:`<div class="m-toolbar"><b>3(x−2)=12</b><div class="fade-control"><button data-level="0" class="active">完整示范</button><button data-level="1">留 1 空</button><button data-level="2">留 2 空</button></div></div><div class="fade-example"><div class="fade-row"><b>1</b><code>3x − 6 = 12</code><span>展开括号</span></div><div class="fade-row" data-r2><b>2</b><code>3x = 18</code><span>两边加 6</span></div><div class="fade-row" data-r3><b>3</b><code>x = 6</code><span>两边除以 3</span></div></div><div class="m-feedback" data-out>完整例题用于建立 schema；连续成功后，系统从最后一步开始留空。</div>`,
 init(r){$$('[data-level]',r).forEach(b=>b.onclick=()=>{$$('[data-level]',r).forEach(x=>x.classList.remove('active'));b.classList.add('active');let l=+b.dataset.level;$('[data-r3] code',r).innerHTML=l>=1?'<input aria-label="第三步" placeholder="填写结果">':'x = 6';$('[data-r2] code',r).innerHTML=l>=2?'<input aria-label="第二步" placeholder="填写等价式">':'3x = 18';$('[data-out]',r).textContent=l===0?'完整示范：先关注子目标和理由。':l===1?'最后一步留空：学生只承担最小的新负担。':'两个步骤留空：如果提示成本升高，系统应退回上一档，而不是继续撤。'})}},
 {id:'M08',kind:'diagnostic',symbol:'✕',name:'第一个无效步骤',en:'First-invalid-step Probe',claim:'要求学生找最早不再等价的一步；后面的计算可能局部正确，但已经建立在错误状态上。',trigger:'只看最终答案无法区分概念错误、变换错误和后续算术错误。',success:'准确定位第一处，并说出被破坏的结构或条件。',fade:'从给定四行，到学生自己标记解题记录中的分叉点。',not:'不是让学生找“所有错”；先找第一个错误才能诊断真正原因。',slots:['学生过程','正确前缀','错误类型','下一探针'],origin:'已有 catalog seed；这里给出可直接操作的诊断 UI。',contract:'input: learner_steps[]\naction: select_first_invalid\noutput: first_invalid_index + error_family\nnext_probe: based_on_error_family',
 demo:`<div class="m-toolbar"><b>学生解：2(x−3)=x+5</b><span>点最早失效的一行</span></div><div class="invalid-list"><button class="invalid-step" data-i="0">2x − 6 = x + 5</button><button class="invalid-step" data-i="1">2x = x + 5 − 6</button><button class="invalid-step" data-i="2">x = −1</button><button class="invalid-step" data-i="3">检验：2(−1−3) ≠ −1+5</button></div><div class="m-feedback" data-out>不要从最终答案倒推；逐行问“这一步与上一行是否等价”。</div>`,
 init(r){$$('[data-i]',r).forEach(b=>b.onclick=()=>{$$('[data-i]',r).forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');let i=+b.dataset.i;$('[data-out]',r).innerHTML=i===1?'<b>定位正确：</b>从 2x−6=x+5 到 2x=x+5−6，把 −6 移到右边时符号应变为 +6。下一探针应检查“逆运算”，不是再做整题。':`这行${i===0?'仍与原式等价':'已经受前面错误影响'}。继续向前找第一处分叉。`})}},
 {id:'M09',kind:'scaffold',symbol:'§',name:'子目标标记器',en:'Subgoal Labels',claim:'把长解法分成“建立表示—化简结构—求解—验证”等有意义阶段，避免学生只记局部操作。',trigger:'学生会模仿每一步，却不知道整段步骤在完成什么目标。',success:'能在新题中自己命名下一子目标，并选择与之匹配的操作。',fade:'先撤每一步理由，再撤子目标标题，让学生自行分段。',not:'不是把 Step 1/2/3 换成更长标题；子目标必须跨越多个局部操作。',slots:['完整步骤','子目标边界','目标标签','迁移题'],origin:'借鉴 edulab 分步模型，但把 step 高亮提升为 subgoal schema。',contract:'input: steps[] + subgoal_boundaries\naction: label_chunk\noutput: predicted_next_subgoal\nfade: step_reason -> subgoal_label',
 demo:`<div class="subgoals"><div class="subgoal"><small>子目标 A · 建立可计算表示</small><code>设直线 x=my+c，与椭圆联立</code></div><div class="subgoal"><small>子目标 B · 避免直接求根</small><code>用韦达得到 y₁+y₂ 与 y₁y₂</code></div><div class="subgoal"><small>子目标 C · 把目标量改写成参数函数</small><code>MA·MB = g(m)</code></div><div class="subgoal"><small>子目标 D · 检查端点可达性</small><code>水平线 / 竖直线是否合法？</code></div></div><div class="m-feedback">步骤可以换题而变化，但“建表示—用结构—改写目标—检查边界”可以迁移。</div>`},
 {id:'M10',kind:'scaffold',symbol:'∵',name:'自解释提示',en:'Targeted Self-explanation',claim:'只在决定性步骤问“为什么允许这样做”，并提供理由类型，不要求学生把整段解法复述一遍。',trigger:'学生能复现步骤，但换数字或题面就不知道为什么这样做。',success:'理由指向数学性质而不是“老师这么教”或“为了更简单”。',fade:'从理由选项到开放解释，再到只在新结构处提问。',not:'不是每行都问 why；频繁解释会打断数学工作并变成语言负担。',slots:['关键步骤','目标性质','近似错误理由','反馈'],origin:'新 scaffold：在完整 worked example 与独立解题之间建立 schema。',contract:'trigger: decisive_step_only\naction: choose_or_generate_reason\noutput: property_invoked\nfade: choices -> open -> exceptional_only',
 demo:`<div class="reason-board"><h3>为什么可以把方程两边同时除以 3？</h3><p class="worked-equation">3x = 18　→　x = 6</p><div class="reason-choice"><button data-r="same">对等式两边做相同非零倍除法，解集不变</button><button data-r="smaller">因为数字会变小，更容易计算</button><button data-r="move">因为 3 可以移到右边</button><button data-r="cancel">因为所有 3 都能随时约掉</button></div><div class="m-feedback" data-out>选择支持这一步的数学性质。</div></div>`,
 init(r){$$('[data-r]',r).forEach(b=>b.onclick=()=>{$$('[data-r]',r).forEach(x=>x.classList.remove('on'));b.classList.add('on');$('[data-out]',r).innerHTML=b.dataset.r==='same'?'<b>理由成立：</b>关键是“等式两边”“相同操作”“除数非零”，不是视觉上的移项。':'这个说法可能描述操作感受，但没有保证新方程与旧方程解集相同。'})}},
 {id:'M11',kind:'scaffold',symbol:'↑',name:'错误型提示阶梯',en:'Error-specific Hint Ladder',claim:'提示不是从模糊到答案的一条通用阶梯；不同错误家族应进入不同的下一步。',trigger:'学生卡住，但“再想想”“看公式”无法区分缺概念、缺策略还是算术失误。',success:'在最低成本且与错误类型匹配的提示后恢复独立工作。',fade:'同类错误连续两次在轻提示级解决后，下一次先等待自修。',not:'不要无论什么错误都按“提示—更多提示—答案”机械升级。',slots:['错误家族','轻提示','区分性问题','回退组件'],origin:'借鉴英语反馈阶梯形式，但改成数学 error-family routing。',contract:'input: error_family + learner_history\naction: smallest_discriminating_hint\noutput: hint_cost + recovery\nescalate: family_specific_component',
 demo:`<div class="hint-stage"><h3>观察：学生把 (a+b)² 写成 a²+b²</h3><div class="hint-line">Level 1：先画一个边长 a+b 的正方形，应该分成几块？</div><div class="hint-line locked">Level 2：指出遗漏的是两块 ab 长方形。</div><div class="hint-line locked">Level 3：给出 a²+2ab+b²，并要求重建。</div><button data-hint>再给一级</button><div class="m-feedback" data-out>这里诊断为“结构分解缺失”，所以回到面积模型；不是再背公式。</div></div>`,
 init(r){let n=0;$('[data-hint]',r).onclick=()=>{let locked=$$('.locked',r);if(locked[n])locked[n++].classList.remove('locked');$('[data-out]',r).textContent=n===1?'二级提示已经暴露缺少的组成部分，但仍让学生自己写系数。':n===2?'完整模型已给出；下一题必须换数字或换图形重建，不能停在抄答案。':'已无更多提示。'}}},
 {id:'M12',kind:'scaffold',symbol:'⇄',name:'策略对照台',en:'Strategy Comparison',claim:'并排比较两条正确路线的中间结构、适用条件和认知成本，而不是只比较谁步骤少。',trigger:'学生掌握一种算法后，把它用于所有题；或认为更短就一定更好。',success:'能根据题目结构选择策略，并说明选择依据。',fade:'先撤系统给出的优缺点，再让学生自己为新题选策略。',not:'不是同题展示两个答案；比较对象是关键中间结构和适用条件。',slots:['同一问题','两条策略','结构特征','选择规则'],origin:'新 scaffold：补足现有可视化与单路线 worked solution。',contract:'input: problem + strategies[]\naction: compare_intermediate_structure\noutput: strategy_choice + criterion\nfade: annotated -> unannotated',
 demo:`<div class="m-toolbar"><b>方程组：2x+y=7；2x−y=1</b></div><div class="strategy-compare"><div class="strategy"><h3>代入法</h3><code>y=7−2x<br>2x−(7−2x)=1<br>4x=8</code><p>需要先孤立变量，括号与符号负担较高。</p></div><div class="strategy"><h3>消元法</h3><code>(2x+y)+(2x−y)=8<br>4x=8</code><p>y 的系数互为相反数，可以一步消去。</p></div></div><div class="m-feedback">不是因为消元“更高级”，而是这道题的系数结构让它保留最少中间负担。</div>`},
 {id:'M13',kind:'diagnostic',symbol:'¬',name:'边界与反例探针',en:'Boundary / Counterexample Probe',claim:'让学生主动寻找让猜想失效的最小例子，区分“看起来经常成立”与“对所有对象成立”。',trigger:'学生根据少量正例快速泛化，或只会验证不会否证。',success:'构造有效反例，并指出猜想缺少的条件。',fade:'从给参数输入，到学生自己选择对象，再到自己改写命题。',not:'不是系统展示一个反例；学生必须控制例子并看到哪项条件被击穿。',slots:['学生猜想','输入范围','最小反例','修正版命题'],origin:'新 diagnostic；与动态不变量、充分必要条件工具组合。',contract:'input: conjecture + domain\naction: construct_counterexample\noutput: falsifying_case + missing_condition\nnext: revise_claim',
 demo:`<div class="counterexample"><div class="identity">√(a+b) = √a + √b　？</div><div class="counter-inputs"><label>a <input data-a type="number" value="1"></label><label>b <input data-b type="number" value="1"></label><button data-test>检验</button></div><div class="m-feedback" data-out>选择 a、b，尝试让等式两边不相等。</div></div>`,
 init(r){$('[data-test]',r).onclick=()=>{let a=+$('[data-a]',r).value,b=+$('[data-b]',r).value,l=Math.sqrt(a+b),rr=Math.sqrt(a)+Math.sqrt(b),ok=Math.abs(l-rr)<1e-8;$('[data-out]',r).innerHTML=ok?`此例两边都为 ${l.toFixed(3)}，没有否证。试试两个都为正的数。`:`<b>反例成立：</b>左边 ${l.toFixed(3)}，右边 ${rr.toFixed(3)}。猜想一般不成立；当 a=0 或 b=0 等特殊条件下才相等。`}}},
 {id:'M14',kind:'scaffold',symbol:'∎',name:'证明骨架架构器',en:'Proof Skeleton',claim:'给出主张与关键中间命题，但让学生选择理由和顺序；支持的是证明结构，不是代写证明。',trigger:'学生知道结论和相关定理，却不知道从哪里开始组织论证。',success:'能把理由绑定到相应推理边，并在撤掉骨架后重建。',fade:'理由库 → 空白理由 → 空白中间命题 → 独立证明。',not:'不是把完整证明拆成可排序句子；那只测阅读与排序。',slots:['目标命题','中间命题','理由库','非充分理由'],origin:'新 scaffold；可调用 edulab 精确几何模型提供可信图形与数值。',contract:'input: claim + proof_graph + reason_bank\naction: bind_reason_to_edge\noutput: proof_structure + invalid_reason\nfade: reasons -> nodes -> none',
 demo:`<div class="proof-board"><div class="proof-column"><h3>证明骨架</h3><p>AB = AC</p><p>↓ <button data-slot="1">选择理由</button></p><p>∠B = ∠C</p><p>↓ <button data-slot="2">选择理由</button></p><p>底边两侧性质对称</p></div><div class="proof-column"><h3>理由库</h3><button class="proof-chip" data-reason="等边对等角">等边对等角</button><button class="proof-chip" data-reason="三角形内角和">三角形内角和</button><button class="proof-chip" data-reason="已知条件">已知条件</button></div></div><div class="m-feedback" data-out>先选择一个空槽，再绑定理由。理由必须支持这一条推理边。</div>`,
 init(r){let slot=null;$$('[data-slot]',r).forEach(b=>b.onclick=()=>{slot=b;b.classList.add('active')});$$('[data-reason]',r).forEach(b=>b.onclick=()=>{if(!slot)return;let val=b.dataset.reason;slot.textContent=val;b.classList.add('used');$('[data-out]',r).textContent=val==='等边对等角'&&slot.dataset.slot==='1'?'这条理由支持 AB=AC → ∠B=∠C。现在检查第二条边是否真的需要另一个命题。':'理由必须准确支持当前箭头；“相关定理”不等于“足够理由”。';slot=null})}},
 {id:'M15',kind:'metacog',symbol:'✓',name:'估计—计算—检验',en:'Estimate / Compute / Check',claim:'在精确计算前建立数量级预期，计算后检查符号、范围、单位与原条件。',trigger:'学生把计算器或代数过程当成权威，得到明显不合理答案仍继续。',success:'能在看到精确答案前给出合理范围，并用独立方式检查。',fade:'从四项检查单，逐渐只保留学生最常漏掉的一项。',not:'不是最后加一句“记得检查”；检查必须在流程中产生可保存的证据。',slots:['估计范围','精确任务','独立检查','常漏维度'],origin:'新 metacognitive scaffold；与精确 kernel 输出形成互补。',contract:'input: task + plausible_range + units\naction: estimate_before_compute\noutput: estimate, exact, checks[]\nfade: checklist -> personal_risk_only',
 demo:`<div class="monitor"><h3>19.8 × 5.1 大约是多少？</h3><div class="estimate-scale"><i class="estimate-marker"></i></div><div class="predict-options"><button data-est="10">约 10</button><button data-est="100">约 100</button><button data-est="1000">约 1000</button></div><button data-calc disabled>再看精确计算</button><div class="reveal-panel" data-result><b>19.8 × 5.1 = 100.98</b><p>范围检查：20×5≈100，所以结果数量级合理。</p></div></div>`,
 init(r){$$('[data-est]',r).forEach(b=>b.onclick=()=>{$$('[data-est]',r).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('[data-calc]',r).disabled=false;$('[data-result]',r).dataset.est=b.dataset.est});$('[data-calc]',r).onclick=()=>{$('[data-result]',r).classList.add('show');let ok=$('[data-result]',r).dataset.est==='100';$('[data-result]',r).insertAdjacentHTML('beforeend',ok?'<p>你的预期与结果一致。</p>':'<p>精确结果暴露了原估计的数量级问题；先修正估计，而不是只接受计算器。</p>')}}}
];

const ROUTES=[
 {name:'从符号搬运到等价变换',time:'20–30 MIN',desc:'学生会移项但不理解保持了什么；先让结构可见，再定位第一处分叉。',ids:['M05','M08','M10','M07']},
 {name:'从看动画到建立函数模型',time:'25 MIN',desc:'把联动可视化变成预测工具，再用系统变例和反例检验参数模型。',ids:['M06','M01','M03','M13']},
 {name:'几何不变量到证明',time:'30 MIN',desc:'先在动态变化中提出不变量，再把经验判断组织成有理由的证明结构。',ids:['M02','M13','M14','M10']},
 {name:'逼近概念微体验',time:'15 MIN',desc:'先预测误差方向，再操作逼近过程；最后隐藏误差读数让学生估计。',ids:['M06','M04','M15']},
 {name:'一题多解策略课',time:'25 MIN',desc:'比较中间结构与适用条件，形成可迁移的策略选择标准。',ids:['M09','M12','M15']},
 {name:'卡住时的最便宜诊断',time:'5–10 MIN',desc:'先定位第一个无效步骤或构造边界例，再按错误家族给最低成本提示。',ids:['M08','M13','M11']}
];

const WORKED=[
 {phase:'MODEL',name:'完整例题，但先看结构',support:'完整步骤 + 子目标标签',evidence:'学生能指出“展开—隔离—求解”三个子目标',fade:'下一题先撤最后一步',screen:`<h2>例题：解 3(x−2)=12</h2><div class="worked-equation">3(x−2)=12</div><div class="worked-lines"><div class="worked-line"><b>展开</b><code>3x−6=12</code></div><div class="worked-line"><b>隔离</b><code>3x=18</code></div><div class="worked-line"><b>求解</b><code>x=6</code></div></div><div class="worked-prompt">先不抄步骤：这三行分别完成了什么子目标？</div>`},
 {phase:'PREDICT',name:'下一步先承诺',support:'三选一预测',evidence:'学生选择“两边加 6”并引用等价保持',fade:'连续两次正确后改为开放输入',screen:`<h2>相似题：4(x−3)=20</h2><div class="worked-equation">4x−12=20</div><div class="worked-prompt"><b>下一步最适合做什么？</b><br><button>两边加 12</button> <button>两边除以 4</button> <button>只把 12 移过去</button></div>`},
 {phase:'EXPLAIN',name:'解释决定性一步',support:'理由选项',evidence:'理由包含“两边、相同操作、解集不变”',fade:'下一题撤理由选项',screen:`<h2>为什么这一步保持等价？</h2><div class="worked-equation">4x−12=20 → 4x=32</div><div class="worked-prompt">不是因为“移项要变号”。请选择真正保证等价的性质：<br><button>等式两边同时加 12</button> <button>数字更简单</button></div>`},
 {phase:'COMPLETE',name:'步骤开始消失',support:'两个 completion slots',evidence:'无提示完成；hint_cost ≤ 1',fade:'把空缺再向前移动',screen:`<h2>Completion problem</h2><div class="worked-equation">5(x+1)=30</div><div class="worked-lines"><div class="worked-line"><b>展开</b><code>5x+5=30</code></div><div class="worked-line"><b>隔离</b><input placeholder="填写等价式"></div><div class="worked-line"><b>求解</b><input placeholder="填写 x"></div></div>`},
 {phase:'DIAGNOSE',name:'处理一个近似错误例',support:'第一个无效步骤探针',evidence:'定位概念错误，而非只说答案错',fade:'下次把错误混入自己的草稿',screen:`<h2>别人哪里第一次走错？</h2><div class="worked-lines"><div class="worked-line"><b>1</b><code>2(x+4)=18</code></div><div class="worked-line"><b>2</b><code>2x+4=18</code></div><div class="worked-line"><b>3</b><code>2x=14</code></div><div class="worked-line"><b>4</b><code>x=7</code></div></div><div class="worked-prompt">点击或指出最早失效的一行，并解释分配律漏掉了什么。</div>`},
 {phase:'TRANSFER',name:'独立题与自检',support:'只保留个人风险检查',evidence:'独立完成 + 代回验证',fade:'全部撤除，错误才重新触发',screen:`<h2>现在独立解决</h2><div class="worked-equation">7(2x−1)=35</div><textarea rows="5" style="width:100%;margin-top:15px" placeholder="写下你的过程…"></textarea><div class="worked-prompt">完成后只做两项检查：展开时是否乘到每一项？把答案代回原式是否成立？</div>`}
];

let selected='M01',filter='all',sequence=[],worked=0;
const byId=id=>TOOLS.find(x=>x.id===id);
function renderFilters(){let box=$('#math-filters');box.innerHTML=Object.entries(FILTERS).map(([k,v])=>`<button data-filter="${k}" class="${k===filter?'active':''}"><span>${v}</span><i>${k==='all'?TOOLS.length:TOOLS.filter(t=>t.kind===k).length}</i></button>`).join('');$$('[data-filter]',box).forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderFilters();renderList()})}
function renderList(){let list=TOOLS.filter(t=>filter==='all'||t.kind===filter),html='',g='';list.forEach(t=>{if(t.kind!==g){g=t.kind;html+=`<div class="math-group">${GROUPS[g]}</div>`}html+=`<button data-tool="${t.id}" class="math-item ${t.id===selected?'active':''}"><span class="symbol">${t.symbol}</span><span><b>${t.name}</b><small>${t.en}</small></span><span class="id">${t.id}</span></button>`});$('#math-list').innerHTML=html;$$('[data-tool]').forEach(b=>b.onclick=()=>{selected=b.dataset.tool;renderList();renderStage()});if(!list.some(t=>t.id===selected)&&list[0]){selected=list[0].id;renderStage()}}
function renderStage(){let t=byId(selected);$('#math-stage').innerHTML=`<header class="math-stage-head"><span>${t.symbol}</span><div><h2>${t.name}</h2><p>${t.claim}</p></div><button id="add-math">＋ 加入链路</button></header><div class="math-preview-label">可直接操作的课堂界面</div><div class="math-preview">${t.demo}</div>`;$('#math-inspector').innerHTML=`<section class="math-card"><h3>老师何时调用</h3><dl><dt>TRIGGER</dt><dd>${t.trigger}</dd><dt>SUCCESS SIGNAL</dt><dd>${t.success}</dd><dt>FADE</dt><dd>${t.fade}</dd></dl></section><section class="math-card"><h3>内容槽</h3><div class="math-slots">${t.slots.map(s=>`<span>${s}</span>`).join('')}</div><dl><dt>PROVENANCE</dt><dd>${t.origin}</dd></dl></section><section class="math-card math-refusal"><h3>它不是什么</h3><p>${t.not}</p></section><pre class="math-contract">${t.contract}</pre>`;$('#add-math').onclick=()=>{sequence.push(t.id);renderSequence(true)};if(t.init)t.init($('.math-preview'))}
function renderRoutes(){let box=$('#route-grid');box.innerHTML=ROUTES.map((r,i)=>`<article class="route-card"><small>${r.time} · ROUTE ${String(i+1).padStart(2,'0')}</small><h3>${r.name}</h3><p>${r.desc}</p><div class="route-flow">${r.ids.map((id,j)=>`${j?'<b>→</b>':''}<span>${id} ${byId(id).name}</span>`).join('')}</div><button data-route="${i}">载入本节课链路</button></article>`).join('');$$('[data-route]',box).forEach(b=>b.onclick=()=>{sequence=[...ROUTES[+b.dataset.route].ids];renderSequence(true)})}
function renderSequence(open=false){$('#sequence-count').textContent=sequence.length;$('#sequence-items').innerHTML=sequence.length?sequence.map((id,i)=>`<div class="sequence-item"><span>${i+1}</span><div><b>${id} ${byId(id).name}</b><small>${byId(id).success}</small></div><button data-remove="${i}">×</button></div>`).join(''):'<p>还没有组件。可以从工具库加入，或载入一条教学链路。</p>';$$('[data-remove]').forEach(b=>b.onclick=()=>{sequence.splice(+b.dataset.remove,1);renderSequence()});let checks=[];if(sequence.every(id=>byId(id).kind==='content')&&sequence.length)checks.push(['warn','这条链路只有内容可视化，没有要求学生预测、解释、诊断或完成。']);if(sequence.includes('M07')&&!sequence.some(id=>['M09','M10'].includes(id)))checks.push(['warn','worked-example fading 前没有结构或自解释支持，学生可能只是在填空。']);if(sequence[0]==='M11')checks.push(['warn','还没有区分错误家族就开始提示；先用诊断探针。']);if(sequence.some(id=>['M08','M13'].includes(id)))checks.push(['ok','包含区分性诊断，Agent 可以根据证据改路。']);if(sequence.some(id=>['M07','M09','M10','M15'].includes(id)))checks.push(['ok','包含明确 fade 条件，支持不会永久留在屏幕上。']);$('#sequence-check').innerHTML=checks.map(c=>`<div class="sequence-check ${c[0]==='warn'?'warn':''}">${c[1]}</div>`).join('');if(open)toggleSequence(true)}
function toggleSequence(on){$('#math-sequence').classList.toggle('open',on);$('#math-scrim').classList.toggle('show',on);$('#math-sequence').setAttribute('aria-hidden',String(!on))}
function renderWorked(){let rail=$('#worked-steps');rail.innerHTML=WORKED.map((w,i)=>`<button data-work="${i}" class="${i===worked?'active':''}"><small>${String(i+1).padStart(2,'0')} · ${w.phase}</small><b>${w.name}</b></button>`).join('');$$('[data-work]',rail).forEach(b=>b.onclick=()=>{worked=+b.dataset.work;renderWorked()});let w=WORKED[worked];$('#worked-board').innerHTML=w.screen;$('#worked-agent').innerHTML=`<h3>Agent 在这一阶段做什么</h3><dl><dt>SUPPORT</dt><dd>${w.support}</dd><dt>OBSERVE</dt><dd>${w.evidence}</dd><dt>FADE / NEXT</dt><dd>${w.fade}</dd></dl>`}
function setView(v){$$('.math-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.math-view').forEach(x=>x.classList.toggle('active',x.id===v+'-view'));let c={library:['CONTENT × SCAFFOLDING','可视化之后，学生下一步要做什么？'],routes:['EVIDENCE-ROUTED PATHWAYS','让学生证据决定下一步，而不是活动顺序。'],worked:['WORKED EXAMPLE FADING','完整示范怎样逐步消失。']}[v];$('#math-kicker').textContent=c[0];$('#math-title').textContent=c[1]}
$$('.math-nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#open-sequence').onclick=()=>toggleSequence(true);$('#close-sequence').onclick=()=>toggleSequence(false);$('#math-scrim').onclick=()=>toggleSequence(false);$('#clear-sequence').onclick=()=>{sequence=[];renderSequence()};
renderFilters();renderList();renderStage();renderRoutes();renderSequence();renderWorked();
