import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(import.meta.dirname, '..');

function extractMathLibrary() {
  const source = fs.readFileSync(path.join(root, 'library/math-viz-kit/index.html'), 'utf8');
  const match = source.match(/const TOOLS\s*=\s*(\[[\s\S]*?\n\s*\]);/);
  if (!match) throw new Error('Could not find math-viz-kit TOOLS array');
  const tools = vm.runInNewContext(`(${match[1]})`);
  return tools.map((tool, index) => ({
    id: `MV${String(index + 1).padStart(3, '0')}`,
    kind: 'asset',
    family: 'asset',
    symbol: '▧',
    name: tool.title,
    en: `${tool.grade} · ${tool.topic}`,
    claim: tool.desc,
    trigger: `教学目标涉及“${tool.topic}”，需要学生直接操作对象、观察变化或比较结果。`,
    success: `学生能用操作结果解释“${tool.desc}”中的核心关系，而不只是完成拖动。`,
    fade: '当学生能够先预测并用数学语言解释关系时，撤掉操作提示，只保留必要表征。',
    not: '不是独立于教学问题的展示动画；它是可被脚手架调用的内容底座。',
    slots: [tool.grade, tool.topic, tool.cogn, `难度${tool.diff}`, `优先${tool.prio}`],
    origin: `math-viz-kit 全量资产 · ${tool.file}`,
    contract: `type: content_asset\ngrade: ${tool.grade}\ntopic: ${tool.topic}\ncognitive_action: ${tool.cogn}\ndifficulty: ${tool.diff}\npriority: ${tool.prio}`,
    previewUrl: `../library/math-viz-kit/${tool.file}`,
    search: `${tool.title} ${tool.desc} ${tool.grade} ${tool.topic} ${tool.cogn} ${tool.diff} ${tool.prio}`
  }));
}

function extractEnglish() {
  const source = fs.readFileSync(path.join(root, 'gold/english/english-scaffold-studio.html'), 'utf8');
  const start = source.indexOf('const families=');
  const end = source.indexOf('const grid=', start);
  if (start < 0 || end < 0) throw new Error('Could not find English skill data');
  const context = {};
  vm.runInNewContext(`${source.slice(start, end)}\nthis.result={families,skills,genericDemo,yamlFor};`, context);
  const {families, skills, genericDemo, yamlFor} = context.result;
  const familyKind = {perception:'scaffold', meaning:'scaffold', reason:'scaffold', production:'scaffold', feedback:'scaffold', meta:'metacog', reg:'regulation'};
  const familyIcon = {perception:'耳', meaning:'义', reason:'理', production:'说', feedback:'返', meta:'镜', reg:'调'};
  const tools = skills.map((skill, index) => ({
    id: `E${String(index + 1).padStart(2, '0')}`,
    sourceId: skill.id,
    kind: familyKind[skill.family],
    family: skill.family,
    symbol: familyIcon[skill.family],
    name: skill.name,
    en: `${skill.cn} · ${families[skill.family][1]}`,
    claim: skill.description,
    trigger: skill.trigger,
    success: skill.success,
    fade: `命中成功信号后减少或撤掉“${skill.cn}”；若失败，只升级到 ${skill.next}。`,
    not: skill.family === 'reg' ? '不是永久降低要求；使用后必须回到原任务验证。' : '不是一段通用解释；它必须由学习证据触发，并在成功后撤走。',
    slots: ['目标语料', '学习者证据', '成功信号', '升级条件'],
    origin: 'English Scaffold Studio · professor-oriented seed',
    contract: yamlFor(skill),
    demo: genericDemo(skill),
    search: `${skill.name} ${skill.cn} ${skill.description} ${skill.trigger} ${skill.success}`
  }));
  const bySource = Object.fromEntries(tools.map(tool => [tool.sourceId, tool.id]));
  const routes = [
    ['听不见 should have', '学生连续重听，仍把 should’ve 当作 should。', 'attention-cue', 'acoustic-alignment', 'boundary-detection', 'shadowing-support'],
    ['懂了却说不出来', '能解释过去遗憾，但开口时总漏掉 have。', 'sentence-frame', 'partial-completion', 'cue', 'error-reflection'],
    ['used to 三连混淆', '能认出每一个，却无法在新句中做选择。', 'contrast', 'rule-induction', 'minimal-grammar', 'transfer-prompt']
  ].map((route, index) => ({name:route[0], time:`ROUTE ${String(index + 1).padStart(2, '0')}`, desc:route[1], ids:route.slice(2).map(id => bySource[id]).filter(Boolean)}));
  return {tools, routes};
}

const math = extractMathLibrary();
const english = extractEnglish();
const out = `// Generated by scripts/build_unified_studio_data.mjs. Do not edit by hand.\nwindow.EDUOS_MATH_LIBRARY=${JSON.stringify(math, null, 2)};\nwindow.EDUOS_ENGLISH_STUDIO=${JSON.stringify(english, null, 2)};\n`;
fs.mkdirSync(path.join(root, 'studios/assets'), {recursive:true});
fs.writeFileSync(path.join(root, 'studios/assets/generated-data.js'), out);
console.log(`Generated ${math.length} math assets and ${english.tools.length} English components.`);
